### ISSUE TITLE
1.0.1发版问题

### ISSUE THREAD

**Issue by woniu163** [SDBridge/SDBridgeKotlin#1]
implementation 'com.github.SDBridge:SDBridgeKotlin:1.0.1' 的包应该还没发，现在maven仓库还是1.0.0的包

**Comment by housenkui** [comment]
感谢你的提醒 README写错了，1.0.0目前就是最新的.

**Comment by woniu163** [comment]
顺便请教一下，SDBridge.js这个文件，是不是需要在html里面引入才行

**Comment by housenkui** [comment]
不用的. Demo.html就没有用这个js文件，这个js目的是演示给h5开发看得，因为这个js文件是webpack打包出来的.

我晚上出一个视频教程吧.

**Comment by housenkui** [comment]
@woniu163 介绍里面已经添加了视频. 
也可以从点[这里](https://search.bilibili.com/all?vt=53806197&keyword=SDBridgeKotlin&from_source=webtop_search&spm_id_from=333.788).

**Comment by woniu163** [comment]
收到，感谢
