### ISSUE TITLE
连续多次打开webView，js注册不了

### ISSUE THREAD

**Issue by gudao20080** [SDBridge/SDBridgeKotlin#2]
我(Android)这边有个WebView页面的Activity，连续打开，关闭，大约有10次,  就会发现有那么一次js注册不进去(web端同事设置了一个轮询获取注册对象loading, loading一直在)。关闭activity,再打开，又正常了。(不知道是哪里出的问题，我不懂js)

**Comment by housenkui** [comment]
您好，你看了我的视频介绍了吗？ 这里有常见问题，有具体的步骤
 https://www.bilibili.com/video/BV1534y1E7P6?spm_id_from=333.337.search-card.all.click

**Comment by housenkui** [comment]
https://github.com/SDBridge/TypeScriptDemo 让h5的同事看一下这个库，当安卓bridge没有成功挂载到window上是，h5自己挂载.

**Comment by housenkui** [comment]
你自己也看一下视频哦
