### ISSUE TITLE
在android手持终端上失效

### ISSUE THREAD

**Issue by qinyang1018** [SDBridge/SDBridgeKotlin#3]
android 9.0

**Comment by housenkui** [comment]
https://search.bilibili.com/all?vt=53806197&keyword=SDBridgeKotlin&from_source=webtop_search&spm_id_from=333.788
看一下集成视频 
@qinyang1018

**Comment by housenkui** [comment]
是h5的 window的bridge 对象没有挂载成功吗？
https://www.bilibili.com/video/BV1534y1E7P6?spm_id_from=333.337.search-card.all.click
常见问题汇总，你看了吗？
