### ISSUE TITLE
WebViewClient Error Android 7.1.2

### ISSUE THREAD

**Issue by langaoyang** [SDBridge/SDBridgeKotlin#5]
Uncaugth ReferenceError : WebViewJavascriptBridge is not defined:1:1 
ReferenceError:WebViewJavascriptBridget is not defined

**Comment by housenkui** [comment]
https://www.bilibili.com/video/BV1534y1E7P6?spm_id_from=333.337.search-card.all.click&vd_source=cd80c47929fafb873ff1a9fb57ac09f4  可以看这个视频
